//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVEditor.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSVEditor.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Above.
        /// </summary>
        public static string AddLineAbove {
            get {
                return ResourceManager.GetString("AddLineAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Below.
        /// </summary>
        public static string AddLineBelow {
            get {
                return ResourceManager.GetString("AddLineBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Line Below This Line.
        /// </summary>
        public static string AddLineDownText {
            get {
                return ResourceManager.GetString("AddLineDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Bottom.
        /// </summary>
        public static string AddLineToBottom {
            get {
                return ResourceManager.GetString("AddLineToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Line to the End of File.
        /// </summary>
        public static string AddLineToBottomText {
            get {
                return ResourceManager.GetString("AddLineToBottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Line... Choose placement in the Combo Box.
        /// </summary>
        public static string AddLineTooltipText {
            get {
                return ResourceManager.GetString("AddLineTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Top.
        /// </summary>
        public static string AddLineToTop {
            get {
                return ResourceManager.GetString("AddLineToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Line to the Beggining of File.
        /// </summary>
        public static string AddLineToTopText {
            get {
                return ResourceManager.GetString("AddLineToTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Line Above This Line.
        /// </summary>
        public static string AddLineUpText {
            get {
                return ResourceManager.GetString("AddLineUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load app options from {0}.\nError: {1}.
        /// </summary>
        public static string AppOptionsLoadError {
            get {
                return ResourceManager.GetString("AppOptionsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Options.
        /// </summary>
        public static string AppOptionsName {
            get {
                return ResourceManager.GetString("AppOptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while processing app options.\nError: {0}.
        /// </summary>
        public static string AppOptionsProcessingError {
            get {
                return ResourceManager.GetString("AppOptionsProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving app options.\nError: {0}.
        /// </summary>
        public static string AppOptionsSaveError {
            get {
                return ResourceManager.GetString("AppOptionsSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Editor.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorText {
            get {
                return ResourceManager.GetString("AuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Path:.
        /// </summary>
        public static string BasePathLabel {
            get {
                return ResourceManager.GetString("BasePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last task was cancelled..
        /// </summary>
        public static string CanceledWorkStatus {
            get {
                return ResourceManager.GetString("CanceledWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Process.
        /// </summary>
        public static string CancelProcessText {
            get {
                return ResourceManager.GetString("CancelProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Files.
        /// </summary>
        public static string ChangedFiles {
            get {
                return ResourceManager.GetString("ChangedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commiter.
        /// </summary>
        public static string CommiterText {
            get {
                return ResourceManager.GetString("CommiterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Message.
        /// </summary>
        public static string CommitMessageText {
            get {
                return ResourceManager.GetString("CommitMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Repository.
        /// </summary>
        public static string CommitRepositoryText {
            get {
                return ResourceManager.GetString("CommitRepositoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit on Save.
        /// </summary>
        public static string CommitText {
            get {
                return ResourceManager.GetString("CommitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed successfuly..
        /// </summary>
        public static string CompletedWorkStatus {
            get {
                return ResourceManager.GetString("CompletedWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Editor.
        /// </summary>
        public static string ConfigurationEditorTitle {
            get {
                return ResourceManager.GetString("ConfigurationEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save file {0} to:
        ///{1} ?.
        /// </summary>
        public static string ConfirmSavingImageFileMessage {
            get {
                return ResourceManager.GetString("ConfirmSavingImageFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Saving Image File.
        /// </summary>
        public static string ConfirmSavingImageFileTitle {
            get {
                return ResourceManager.GetString("ConfirmSavingImageFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ContentLabel {
            get {
                return ResourceManager.GetString("ContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find neither image file on disk or implicit placeholder path. Error: {0}.
        /// </summary>
        public static string CouldNotFindImagePathError {
            get {
                return ResourceManager.GetString("CouldNotFindImagePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new {0} directory in {1}.
        /// </summary>
        public static string CreatingNewDirectoryInDirectoryFormat {
            get {
                return ResourceManager.GetString("CreatingNewDirectoryInDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new {0} in {1}.
        /// </summary>
        public static string CreatingNewFileInDirectoryFormat {
            get {
                return ResourceManager.GetString("CreatingNewFileInDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv file configurations.
        /// </summary>
        public static string CsvFileConfigurationsText {
            get {
                return ResourceManager.GetString("CsvFileConfigurationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentImage.
        /// </summary>
        public static string CurrentImageText {
            get {
                return ResourceManager.GetString("CurrentImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0} with date format of &quot;{1}&quot; results to: {2}..
        /// </summary>
        public static string DateFormatResultFormat {
            get {
                return ResourceManager.GetString("DateFormatResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Formating for Generated Date:.
        /// </summary>
        public static string DateUriLabelText {
            get {
                return ResourceManager.GetString("DateUriLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string DefaultDirectoryName {
            get {
                return ResourceManager.GetString("DefaultDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files....
        /// </summary>
        public static string DefaultFilesName {
            get {
                return ResourceManager.GetString("DefaultFilesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Current File and Save.
        /// </summary>
        public static string DeleteCurrentFileAndSaveText {
            get {
                return ResourceManager.GetString("DeleteCurrentFileAndSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Current Image.
        /// </summary>
        public static string DeleteCurrentImageText {
            get {
                return ResourceManager.GetString("DeleteCurrentImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete This Line.
        /// </summary>
        public static string DeleteLineText {
            get {
                return ResourceManager.GetString("DeleteLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Column Configurations.
        /// </summary>
        public static string EditColumnConfigurations {
            get {
                return ResourceManager.GetString("EditColumnConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited.
        /// </summary>
        public static string EditedText {
            get {
                return ResourceManager.GetString("EditedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lines.
        /// </summary>
        public static string EditLines {
            get {
                return ResourceManager.GetString("EditLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this line.
        /// </summary>
        public static string EditThisLineText {
            get {
                return ResourceManager.GetString("EditThisLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Personal Access Token first..
        /// </summary>
        public static string EnterPATPrompt {
            get {
                return ResourceManager.GetString("EnterPATPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while checking for GitRepo: {0}.
        /// </summary>
        public static string ErrorCheckingGitRepoFormat {
            get {
                return ResourceManager.GetString("ErrorCheckingGitRepoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading {0}: {1}.
        /// </summary>
        public static string ErrorLoadingFormat {
            get {
                return ResourceManager.GetString("ErrorLoadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error pulling repository. Error: {0}.
        /// </summary>
        public static string ErrorPullingRepositoryFormat {
            get {
                return ResourceManager.GetString("ErrorPullingRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading directory path: {0}.
        /// </summary>
        public static string ErrorReadingDirectoryPathFormat {
            get {
                return ResourceManager.GetString("ErrorReadingDirectoryPathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file extension for file: {0}. Error: {1}.
        /// </summary>
        public static string ErrorReadingFileExtensionFormat {
            get {
                return ResourceManager.GetString("ErrorReadingFileExtensionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving {0}: {1}.
        /// </summary>
        public static string ErrorSavingFormat {
            get {
                return ResourceManager.GetString("ErrorSavingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while staging repository at &quot;{0}&quot;. Error: {1}.
        /// </summary>
        public static string ErrorStagingRepositoryFormat {
            get {
                return ResourceManager.GetString("ErrorStagingRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last task stopped with and error..
        /// </summary>
        public static string ErrorWorkStatus {
            get {
                return ResourceManager.GetString("ErrorWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close Csv Editor.
        /// </summary>
        public static string ExitAndSaveText {
            get {
                return ResourceManager.GetString("ExitAndSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Csv Editor.
        /// </summary>
        public static string ExitAppText {
            get {
                return ResourceManager.GetString("ExitAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} already exists at :
        ///{1} .
        ///Do you want to overwrite this file?.
        /// </summary>
        public static string FileAlreadyExistsOverwriteMessage {
            get {
                return ResourceManager.GetString("FileAlreadyExistsOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file configuration process - configuration NOT FOUND, which should not happen on update..
        /// </summary>
        public static string FileConfigurationNotFoundException {
            get {
                return ResourceManager.GetString("FileConfigurationNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Edited.
        /// </summary>
        public static string FileEdited {
            get {
                return ResourceManager.GetString("FileEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Files (*{0})|*{0}|All files (*.*)|*.*.
        /// </summary>
        public static string FileFilterFormat {
            get {
                return ResourceManager.GetString("FileFilterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileText {
            get {
                return ResourceManager.GetString("FileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the following errors before proceeding:\n\n.
        /// </summary>
        public static string FixErrorsPrompt {
            get {
                return ResourceManager.GetString("FixErrorsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Selection.
        /// </summary>
        public static string FolderSelectionText {
            get {
                return ResourceManager.GetString("FolderSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a GitHub Personal Access Token (requires &apos;repo&apos; and &apos;user&apos; scopes).
        /// </summary>
        public static string GetPATText {
            get {
                return ResourceManager.GetString("GetPATText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed: {0}.
        /// </summary>
        public static string GitAuthFailed {
            get {
                return ResourceManager.GetString("GitAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully authenticated as {0}!.
        /// </summary>
        public static string GitAuthSuccessText {
            get {
                return ResourceManager.GetString("GitAuthSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing staged changes before push....
        /// </summary>
        public static string GitCommitingBeforePushMessage {
            get {
                return ResourceManager.GetString("GitCommitingBeforePushMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Your GitHub email is private and couldn&apos;t be fetched. You can manually enter the email you want to use for commit signatures..
        /// </summary>
        public static string GitCouldntFetchEmailText {
            get {
                return ResourceManager.GetString("GitCouldntFetchEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot push a detached HEAD. Please checkout a branch first..
        /// </summary>
        public static string GitDetachedHeadErrorMessage {
            get {
                return ResourceManager.GetString("GitDetachedHeadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works?&amp;#x0a;1. Generate a PAT using the link below.&amp;#x0a;2. Paste the token into the Password field.&amp;#x0a;3. Click &apos;GitHub Login&apos; to validate and fill in Username/Email.&amp;#x0a;4. This enables secure Git operations and sets your commit signature..
        /// </summary>
        public static string GitHubLoginGuideTooltip {
            get {
                return ResourceManager.GetString("GitHubLoginGuideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Login.
        /// </summary>
        public static string GitHubLoginText {
            get {
                return ResourceManager.GetString("GitHubLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login data ar not correct.
        /// </summary>
        public static string GitLoginEntriesFalsy {
            get {
                return ResourceManager.GetString("GitLoginEntriesFalsy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: For GitHub, you must use a Personal Access Token (PAT). Regular passwords are no longer supported for API access..
        /// </summary>
        public static string GitPATTipText {
            get {
                return ResourceManager.GetString("GitPATTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing credentials for {0}.
        /// </summary>
        public static string GitProvidingCredentialsMessage {
            get {
                return ResourceManager.GetString("GitProvidingCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefSpec: {0}. Ahead by: {1}.
        /// </summary>
        public static string GitPushBranchStateInfoMessage {
            get {
                return ResourceManager.GetString("GitPushBranchStateInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string GitPushButtonText {
            get {
                return ResourceManager.GetString("GitPushButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing local &apos;{0}&apos; ({1}) to remote &apos;{2}&apos; ({3})..
        /// </summary>
        public static string GitPushingLocal {
            get {
                return ResourceManager.GetString("GitPushingLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error pushing repository. Error: {0}.
        /// </summary>
        public static string GitPushingRepositoryErrorMessage {
            get {
                return ResourceManager.GetString("GitPushingRepositoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push status error: {0} - {1}.
        /// </summary>
        public static string GitPushStatusErrorMessage {
            get {
                return ResourceManager.GetString("GitPushStatusErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Push.
        /// </summary>
        public static string GitPushWindowTitle {
            get {
                return ResourceManager.GetString("GitPushWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository commited.
        /// </summary>
        public static string GitRepositoryCommittedMessage {
            get {
                return ResourceManager.GetString("GitRepositoryCommittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository pushed to {0}..
        /// </summary>
        public static string GitRepositoryPushedMessage {
            get {
                return ResourceManager.GetString("GitRepositoryPushedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository staged..
        /// </summary>
        public static string GitRepositoryStagedMessage {
            get {
                return ResourceManager.GetString("GitRepositoryStagedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set upstream tracking for &apos;{0}&apos; to &apos;{1}/{2}&apos;.
        /// </summary>
        public static string GitSettingUpstreamBranch {
            get {
                return ResourceManager.GetString("GitSettingUpstreamBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Setup.
        /// </summary>
        public static string GitSetupWindowTitle {
            get {
                return ResourceManager.GetString("GitSetupWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get Git Status..
        /// </summary>
        public static string GitStatusFailed {
            get {
                return ResourceManager.GetString("GitStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to commit &amp; push..
        /// </summary>
        public static string GitStatusNoChanges {
            get {
                return ResourceManager.GetString("GitStatusNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Status.
        /// </summary>
        public static string GitStatusText {
            get {
                return ResourceManager.GetString("GitStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.
        /// </summary>
        public static string GitText {
            get {
                return ResourceManager.GetString("GitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token does not match the entered username..
        /// </summary>
        public static string GitTokenNotMatchingUser {
            get {
                return ResourceManager.GetString("GitTokenNotMatchingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate token and fetch profile info from GitHub.
        /// </summary>
        public static string GitTokenValidationTooltip {
            get {
                return ResourceManager.GetString("GitTokenValidationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating remote &apos;{0}&apos; URL to: {1}.
        /// </summary>
        public static string GitUpdatingRemoteNameMessage {
            get {
                return ResourceManager.GetString("GitUpdatingRemoteNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task in progress..
        /// </summary>
        public static string IdleWorkStatus {
            get {
                return ResourceManager.GetString("IdleWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Valid Image Files (*.jpg, *.jpeg, *.png, *.webp)|*.png;*.jpg;*.jpeg;*.webp|PNG Files (*.png)|*.png|JPG Files (*.jpg)|*.jpg|JPEG Files (*.jpeg)|*.jpeg|WebP Files (*.webp)|*.webp|All Files (*.*)|*.*.
        /// </summary>
        public static string ImageFilesFilter {
            get {
                return ResourceManager.GetString("ImageFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Relative Path to Save Image Files to:.
        /// </summary>
        public static string ImageUriLabelText {
            get {
                return ResourceManager.GetString("ImageUriLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient rights to read all files in &quot;{0}&quot;..
        /// </summary>
        public static string InsufficientRightsToReadAllFilesFormat {
            get {
                return ResourceManager.GetString("InsufficientRightsToReadAllFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient rights to scan directory at &quot;{0}&quot;. Error: {1}.
        /// </summary>
        public static string InsufficientRightsToScanDirectoryFormat {
            get {
                return ResourceManager.GetString("InsufficientRightsToScanDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditor.
        /// </summary>
        public static string LineEditorText {
            get {
                return ResourceManager.GetString("LineEditorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Editor.
        /// </summary>
        public static string LineEditorTitle {
            get {
                return ResourceManager.GetString("LineEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line:.
        /// </summary>
        public static string LineNrText {
            get {
                return ResourceManager.GetString("LineNrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Directory.
        /// </summary>
        public static string LoadDirectoryText {
            get {
                return ResourceManager.GetString("LoadDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded CSV files.
        /// </summary>
        public static string LoadedCSVFilesText {
            get {
                return ResourceManager.GetString("LoadedCSVFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} loaded from: {1}.
        /// </summary>
        public static string LoadedFromFormat {
            get {
                return ResourceManager.GetString("LoadedFromFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options file not found or invalid. Creating new default options..
        /// </summary>
        public static string LoadOptionsErrorCreatingNewMessage {
            get {
                return ResourceManager.GetString("LoadOptionsErrorCreatingNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the repository failed..
        /// </summary>
        public static string LoadRepositoryFailed {
            get {
                return ResourceManager.GetString("LoadRepositoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Repository....
        /// </summary>
        public static string LoadRepositoryPlaceholder {
            get {
                return ResourceManager.GetString("LoadRepositoryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LoadText {
            get {
                return ResourceManager.GetString("LoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as: {0} ({1})..
        /// </summary>
        public static string LoggedInAsFormat {
            get {
                return ResourceManager.GetString("LoggedInAsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in in option Git -&gt; Setup Git Login Options.
        /// </summary>
        public static string LogInHelpText {
            get {
                return ResourceManager.GetString("LogInHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new file.txt.
        /// </summary>
        public static string NewFileText {
            get {
                return ResourceManager.GetString("NewFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Image.
        /// </summary>
        public static string NewImageText {
            get {
                return ResourceManager.GetString("NewImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Save Path:.
        /// </summary>
        public static string NewSavePathText {
            get {
                return ResourceManager.GetString("NewSavePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected..
        /// </summary>
        public static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no path to display.
        /// </summary>
        public static string NoPathToDisplayText {
            get {
                return ResourceManager.GetString("NoPathToDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Commit not performed - no changes to commit..
        /// </summary>
        public static string NotCommitedError {
            get {
                return ResourceManager.GetString("NotCommitedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Edited.
        /// </summary>
        public static string NotEditedText {
            get {
                return ResourceManager.GetString("NotEditedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory doesn&apos;t contain Git repository..
        /// </summary>
        public static string NotGitRepository {
            get {
                return ResourceManager.GetString("NotGitRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into GitHub for git push automation -&gt;.
        /// </summary>
        public static string NotLoggedToGitInfoText {
            get {
                return ResourceManager.GetString("NotLoggedToGitInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open help window to guide you how to set date format right..
        /// </summary>
        public static string OpenDateFilterGuideWindowTooltip {
            get {
                return ResourceManager.GetString("OpenDateFilterGuideWindowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Git Setup Window.
        /// </summary>
        public static string OpenGitSetupText {
            get {
                return ResourceManager.GetString("OpenGitSetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverviewHeaderText {
            get {
                return ResourceManager.GetString("OverviewHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Current File.
        /// </summary>
        public static string OverwriteCurrentFileText {
            get {
                return ResourceManager.GetString("OverwriteCurrentFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string OverwriteText {
            get {
                return ResourceManager.GetString("OverwriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &quot;{0}&quot; doesn&apos;t contain valid repository. Error: {1}.
        /// </summary>
        public static string PathNotValidRepositoryFormat {
            get {
                return ResourceManager.GetString("PathNotValidRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For GitHub/GitLab, use a Personal Access Token (PAT) instead of your password..
        /// </summary>
        public static string PATOverPasswordPrompt {
            get {
                return ResourceManager.GetString("PATOverPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username..
        /// </summary>
        public static string PleaseEnterUserNamePrompt {
            get {
                return ResourceManager.GetString("PleaseEnterUserNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing File.
        /// </summary>
        public static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull From Remote Repository.
        /// </summary>
        public static string PullRepositoryText {
            get {
                return ResourceManager.GetString("PullRepositoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push To Remote Repository.
        /// </summary>
        public static string PushRepositoryText {
            get {
                return ResourceManager.GetString("PushRepositoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push on Save.
        /// </summary>
        public static string PushText {
            get {
                return ResourceManager.GetString("PushText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw File.
        /// </summary>
        public static string RawFileText {
            get {
                return ResourceManager.GetString("RawFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember This Selection.
        /// </summary>
        public static string RememberSelectionText {
            get {
                return ResourceManager.GetString("RememberSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote repository link.
        /// </summary>
        public static string RemoteLinkText {
            get {
                return ResourceManager.GetString("RemoteLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Name.
        /// </summary>
        public static string RemoteNameText {
            get {
                return ResourceManager.GetString("RemoteNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote &apos;{0}&apos; not found. Adding remote &apos;{0}&apos; with link: {1}.
        /// </summary>
        public static string RemoteOriginNotFoundAddingFormat {
            get {
                return ResourceManager.GetString("RemoteOriginNotFoundAddingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote &apos;{0}&apos; not found and no valid remote link provided in Git Setup..
        /// </summary>
        public static string RemoteOriginNotFoundNoLinkText {
            get {
                return ResourceManager.GetString("RemoteOriginNotFoundNoLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace image file.
        /// </summary>
        public static string ReplaceImageFile {
            get {
                return ResourceManager.GetString("ReplaceImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root directory.
        /// </summary>
        public static string RootDirectory {
            get {
                return ResourceManager.GetString("RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Directory.
        /// </summary>
        public static string RootDirectoryLabel {
            get {
                return ResourceManager.GetString("RootDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string SaveAsText {
            get {
                return ResourceManager.GetString("SaveAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved to: {1}.
        /// </summary>
        public static string SavedToFormat {
            get {
                return ResourceManager.GetString("SavedToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File As.
        /// </summary>
        public static string SaveFileAs {
            get {
                return ResourceManager.GetString("SaveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save edited file before closing CsvEditor?.
        /// </summary>
        public static string SaveFileBeforeExitQuery {
            get {
                return ResourceManager.GetString("SaveFileBeforeExitQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string SaveFileTitle {
            get {
                return ResourceManager.GetString("SaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        public static string SaveImageText {
            get {
                return ResourceManager.GetString("SaveImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} File to:.
        /// </summary>
        public static string SaveNewImageSourceFileTitle {
            get {
                return ResourceManager.GetString("SaveNewImageSourceFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To: .
        /// </summary>
        public static string SaveToText {
            get {
                return ResourceManager.GetString("SaveToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Options.
        /// </summary>
        public static string SaveWindowTitle {
            get {
                return ResourceManager.GetString("SaveWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file failed. Error: .
        /// </summary>
        public static string SavingFailedText {
            get {
                return ResourceManager.GetString("SavingFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another file..
        /// </summary>
        public static string SelectAnotherFileText {
            get {
                return ResourceManager.GetString("SelectAnotherFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainVM.SelectedCsvFile: {0}.
        /// </summary>
        public static string SelectedCsvFileLogFormat {
            get {
                return ResourceManager.GetString("SelectedCsvFileLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorVM, selectedIndexUpdated to {0}.
        /// </summary>
        public static string SelectedIndexUpdatedFormat {
            get {
                return ResourceManager.GetString("SelectedIndexUpdatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file:.
        /// </summary>
        public static string SelectedTextDefault {
            get {
                return ResourceManager.GetString("SelectedTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Predefined Save Path..
        /// </summary>
        public static string SelectPredefinedSavePath {
            get {
                return ResourceManager.GetString("SelectPredefinedSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project root directory.
        /// </summary>
        public static string SelectProjectRootDirectory {
            get {
                return ResourceManager.GetString("SelectProjectRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select value --.
        /// </summary>
        public static string SelectPromptComboBoxText {
            get {
                return ResourceManager.GetString("SelectPromptComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Different Save Path.
        /// </summary>
        public static string SelectSavePathText {
            get {
                return ResourceManager.GetString("SelectSavePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GitVM] Setting up repository..
        /// </summary>
        public static string SettingUpRepositoryText {
            get {
                return ResourceManager.GetString("SettingUpRepositoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging all changes before push....
        /// </summary>
        public static string StagingAllBeforePushMessage {
            get {
                return ResourceManager.GetString("StagingAllBeforePushMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error during commit. Error: {0}.
        /// </summary>
        public static string UnexpectedErrorDuringCommitFormat {
            get {
                return ResourceManager.GetString("UnexpectedErrorDuringCommitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured while reading directories at: &quot;{0}&quot;. Error: {1}.
        /// </summary>
        public static string UnexpectedErrorReadingDirectoriesFormat {
            get {
                return ResourceManager.GetString("UnexpectedErrorReadingDirectoriesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured while scanning directories at: &quot;{0}&quot;. Error: {1}.
        /// </summary>
        public static string UnexpectedErrorScanningDirectoriesFormat {
            get {
                return ResourceManager.GetString("UnexpectedErrorScanningDirectoriesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown state....
        /// </summary>
        public static string UnknownState {
            get {
                return ResourceManager.GetString("UnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating configuration for {0} in {1}.
        /// </summary>
        public static string UpdatingConfigurationFormat {
            get {
                return ResourceManager.GetString("UpdatingConfigurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Secure Token Storage (Windows Credential Manager.
        /// </summary>
        public static string UseSecureTokenStorageText {
            get {
                return ResourceManager.GetString("UseSecureTokenStorageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use This Setup.
        /// </summary>
        public static string UseThisSetupText {
            get {
                return ResourceManager.GetString("UseThisSetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work in progress!.
        /// </summary>
        public static string WorkingWorkStatus {
            get {
                return ResourceManager.GetString("WorkingWorkStatus", resourceCulture);
            }
        }
    }
}
