<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22000.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CredentialManagement" Version="1.0.2" NoWarn="NU1701" />
    <PackageReference Include="LibGit2Sharp" Version="0.30.0" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSVEditor.Core\CSVEditor.Core.csproj" />
  </ItemGroup>

</Project>
